FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt /app
RUN pip3 install -r requirements.txt --no-cache-dir
COPY . .
COPY static/ static/
CMD ["gunicorn", "api_yamdb.wsgi:application", "--bind", "0:8000" ]